# Generated by Django 4.1.7 on 2023-03-03 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact",
            old_name="contact_pcture",
            new_name="contact_picture",
        ),
    ]
